plan:
	terraform plan -var "do_token=`cat ~/.private/do_token`"

apply:
	terraform apply -var "do_token=`cat ~/.private/do_token`" -auto-approve

destroy:
	terraform destroy -var "do_token=`cat ~/.private/do_token`"
